const axios = require('axios');
const fs = require('fs');
const path = require('path');
const FormData = require('form-data');

// ==========================================
// 1. CONFIGURATION & IDENTITY
// ==========================================
const API_BASE = 'http://100.83.30.12:5151';

// Large Token from .env.local
const INSTRUCTOR_TOKEN = 'eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJ1c2VySWQiOjEsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwicGVybWlzc2lvbnMiOlsiQ09VUlNFX0NSRUFURSIsIkNPVVJTRV9VUERBVEUiLCJDT0VSU0VfREVMRVRFIiwiQ09VUlNFX1ZJRVciLCJUT1BJQ19DUkVBVEUiLCJUT1BJQ19VUERBVEUiLCJUT1BJQ19ERUxFVEUiLCJUT1BJQ19WSUVXIiwiQ09OVEVOVF9BREQiLCJDT05URU5UX1VQREFURSIsIkNPTlRFTlRfREVMRVRFIiwiQ09OVEVOVF9WSUVXIiwiQ09OVEVOVF9BQ0NFU1MiLCJWRUhJQ0xFX0FERCIsIlZFSElDTEVfVklFVyIsIlZFSElDTEVfVVBEQVRFIiwiVkVISUNMRV9ERUxFVEUiLCJST1VURV9BREQiLCJST1VURV9WSUVXIiwiUk9VVEVfVVBEQVRFIiwiUk9VVEVfREVMRVRFIiwiRFJJVkVSX0FERCIsIkRSSVZFUl9WSUVXIiwiRFJJVkVSX1VQREFURSIsIkRSSVZFUl9ERUxFVEUiLCJDT05EVUNUT1JfQUREIiwiQ09ORFVDVE9SX1ZJRVciLCJDT05EVUNUT1JfVVBEQVRFIiwiQ09ORFVDVE9SX0RFTEVURSIsIkdQU19BREQiLCJHUFNfVklFVyIsIkdQU19VUERBVEUiLCJHUFNfREVMRVRFIiwiVFJBTlNQT1JUX0FUVEVOREFOQ0VfQUREIiwiVFJBTlNQT1JUX0FUVEVOREFOQ0VfVklFVyIsIlRSQU5TUE9SVF9BVFRFTkRBTkNFX1VQREFURSIsIlRSQU5TUE9SVF9BVFRFTkRBTkNFX0RFTEVURSIsIk1BTkFHRV9DT1VSU0VTIiwiVklFV19DT05URU5UIiwiVklFV19QUk9GSUxFIiwiQkFUQ0hfQ1JFQVRFIiwiQkFUQ0hfVVBEQVRFIiwiQkFUQ0hfREVMRVRFIiwiQkFUQ0hfVklFVyIsIlNFU1NJT05fQ1JFQVRFIiwiU0VTU0lPTl9VUERBVEUiLCJTRVNTSU9OX0RFTEVURSIsIlNFU1NJT05fVklFVyIsIlNFU1NJT05fQ09OVEVOVF9DUkVBVEUiLCJTRVNTSU9OX0NPTlRFTlRfVVBEQVRFIiwiU0VTU0lPTl9DT05URU5UX0RFTEVURSIsIlNFU1NJT05fQ09OVEVOVF9WSUVXIiwiU0VTU0lPTl9DT05URU5UX1BSRVZJRVciLCJTRVNTSU9OX0NPTlRFTlRfRE9XTkxPQUQiLCJDT1VSU0VfQkFUQ0hfU1RBVFNfVklFVyIsIlNUVURFTlRfQkFUQ0hfQ1JFQVRFIiwiU1RVREVOVF9CQVRDSF9VUERBVEUiLCJTVFVERU5UX0JBVENIX0RFTEVURSIsIlNUVURFTlRfQkFUQ0hfVklFVyIsIlNUVURFTlRfQkFUQ0hfVFJBTlNGRVJfQ1JFQVRFIiwiU1RVREVOVF9CQVRDSF9UUkFOU0ZFUl9WSUVXIiwiQVRURU5EQU5DRV9TRVNTSU9OX0NSRUFURSIsIkFUVEVOREFOQ0VfU0VTU0lPTl9WSUVXIiwiQVRURU5EQU5DRV9TRVNTSU9OX1VQREFURSIsIkFUVEVOREFOQ0VfU0VTU0lPTl9ERUxFVEUiLCJBVFRFTkRBTkNFX1JFQ09SRF9DUkVBVEUiLCJBVFRFTkRBTkNFX1JFQ09SRF9VUERBVEUiLCJBVFRFTkRBTkNFX1JFQ09SRF9WSUVXIiwiQVRURU5EQU5DRV9SRUNPUkRfREVMRVRFIiwiRkVFX1RZUEVfQ1JFQVRFIiwiRkVFX1RZUEVfVklFVyIsIkZFRV9UWVBFX1ZJRVdfQUNUSVZFIiwiRkVFX1RZUEVfVVBEQVRFIiwiRkVFX1RZUEVfREVMRVRFIiwiRkVFX1NUUlVDVFVSRV9DUkVBVEUiLCJGRUVfVFlQRV9WSUVXX0FMTCIsIiBGRUVfU1RSVUNUVVJFX1ZJFVdfQllfQ09VUlNFL0JBVENIIiwiRkVFX1NUUlVDVFVSRV9VUERBVEUiLCJGRUVfU1RSVUNUVVJFX0RFTEVURSIsIlNUVURFTlRfRkVFX0FMTE9DQVRJT05fQ1JFQVRFIiwiU1RVREVOVF9GRUVfQUxMT0NBVElPTl9WSUVXX0FMTCIsIlNUVURFTlRfRkVFX0FMTE9DQVRJT05fVklFV19CWV9VU0VSSUQiLCJTVFVERU5UX0ZFRV9BTExPQ0FUSU9OX1VQREFURSIsIlNUVURFTlRfRkVFX0FMTE9DQVRJT05fREVMRVRFIiwiU1RVREVOVF9GRUVfUEFZTUVOVF9DUkVBVEUiLCJTVFVERU5UX0ZFRV9QQVlNRU5UX1ZJFVdfQUxMIiwiU1RVREVOVF9GRUVfUEFZTUVOVF9CWV9VU0VSL0hJU1RPUlkiLCJTVFVERU5UX0ZFRV9QQVlNRU5UX09OTElORV9QUk9DRVNTIiwiRkVFX0RJU0NPVU5UX0NSRUFURSIsIkZFRV9ESVNDT1VOVFNfVklFV19BTEwiLCJGRUVfRElTQ09VTlRTX1ZJFVdfQllfVVNFUklEIiwiRkVFX0RJU0NPVU5UX1VQREFURSIsIkZFRV9ESVNDT1VOVF9ERUxFVEUiLCJGRUVfUkVGVU5EX0NSRUFURSIsIkZFRV9SRUZVTkRfU0VMRl9DUkVBVEUiLCJGRUVfUkVGVU5EX0FDQ0VQVCIsIkZFRV9SRUZVTkRfUkVKRUNUIiwiRkVFX1JFQ0VJUFRfVklFVyIsIkZFRV9SRUNFSVBUX1ZJRVdfQllfUEFZTUVOVElEIiwiQVVESVRfTE9HVFNfVklFVyIsIkJBVFNDSC9DT1VSU0VfUkVQT1JUX1ZJRVciLCJGSU5BTkNJQUxfUkVQT1JUX1ZJRVciLCJQQVlNRU5UX0FMVEVSTkFUSVZFX0NSRUFURSIsIlBBWU1FTlRfQUxURVJOQVRJVkVfVklFV19BTEwiLCJQQVlNRU5UX0FMVEVSTkFUSVZFX1ZJRVdfQUNUSVZFIiwiUEFZTUVOVF9BTFRFUk5BVElWRV9WSUVXX0JZX0lEIiwiUEFZTUVOVF9BTFRFUk5BVElWRV9VUERBVEUiLCJQQVlNRU5UX0FMVEVSTkFUSVZFX0RFTEVURSIsIlNUVURFTlRfSU5TVEFMTE1FTlRfUEhBTl9DUkVBVEUiLCJTVFVERU5UX0lOU1RBTExNRU5UX1BMQU5fUkVTRVQiLCJTVFVERU5UX0lOU1RBTExNRU5UX1BMQU5fVklFV19BTEwiLCJTVFVERU5UX0lOU1RBTExNRU5UX1BMQU5fVklFV19CWV9BTExPQ0FUSU9OIiwiU1RVREVOVF9JTlNUQUxMTUVOVF9QTEFOX1NFTEZfVklFV19CWV9BTExPQ0FUSU9OIiwiU1RVREVOVF9JTlNUQUxMTUVOVF9QTEFOX09WRVJEVUVfVklFVyIsIlNUVURFTlRfSU5TVEFMTE1FTlRfUExBTl9VUERBVEUiLCJMQVRFX0ZFRV9DT05GSUdfDUVSRUFURSIsIkxBVEVfRkVFX0NPTkZJR19WSUVXIiwiTEFURV9GRUVfQ09ORklHX1ZJRVdfQUNUSVZFIiwiTEFURV9GRUVfQ09ORklHX1VQREFURSIsIkxBVEVfRkVFX0NPTkZJR19ERUxFVEUiLCJMQVRFX0ZFRV9QRU5BTFRZX0NSRUFURVIsIkxBVEVfRkVFX1BFTkFMVFlfVklFV19BTEwiLCJMQVRFX0ZFRV9QRU5BTFRZX1ZJRVdfQllfSU5TVEFMTE1FTlQiLCJMQVRFX0ZFRV9QRU5BTFRZX1VQREFURSIsIkxBVEVfRkVFX1BFTkFMVFlfREVMRVRFIiwiTEFURV9GRUVfUEVOQUxUWV9DUkVBVEVfQVBQUFkvV0FJRkVfQVRURU5EQU5DRV9QRU5BTFRZX0NSRUFURSIsIkFUVEVOREFOQ0VfUEVOQUxUWV9WSUVXX0FMTCIsIkFUVEVOREFOQ0VfUEVOQUxUWV9WSUVXX0JZX1VTRVJJRCIsIkFUVEVOREFOQ0VfUEVOQUxUWV9VUERBVEUiLCJBVFRFTkRBTkNFX1BFTkFMVFlfREVMRVRFIiwiRVhBTV9GRUVfTElOS0FHRV9DUkVBVEUiLCJFWEFNX0ZFRV9MSU5LQUdFX1ZJRVdfQUxMIiwiRVhBTV9GRUVfTElOS0FHRV9WSUVXX0JZX1VTRVJJRCIsIkVYQU1fRkVFX0xJTktBR0VfVVBEQVRFIiwiRVhBTV9GRUVfTElOS0FHRV9ERUxFVEUiLCJQQVlNRU5UX05PVElGSUNBVElPTl9DUkVBVEUiLCJQQVlNRU5UX05PVElGSUNBVElPTl9WSUVXX0FMTCIsIlBBWU1FTlRfTk9USUZJQ0FUSU9OX1ZJRVdfQllfVVNFUklEIiwiUEFZTUVOVF9OT1RJRklDQVRJT05fVVBEQVRFIiwiUEFZTUVOVF9OT1RJRklDQVRJT05fREVMRVRFIiwiQVVUT19ERUJJVF9DT05GSUdfQ1JFQVRFIiwiQVVUT19ERUJJVF9DT05GSUdfVklFV19BTEwiLCJBVVRPX0RFQklUX0NPTkFJR19WSUVXX0JZX1VTRVIiLCJBVVRPX0RFQklUX0NPTkZJX1VQREFURSIsIkFVVE9fREVCSVRfQ09ORklHX0RFTEVURSIsIkNVUlJFTkNZX1JBVEVfQ1JFQVRFIiwiQ1VSUkVOQ1lfUkFURV9WSUVXX0FMTCIsIkNVUlJFTkNZX1JBVEVfVklFV19DT05WRVJUIiwiQ1VSUkVOQ1lfUkFURV9VUERBVEUiLCJDVVJSRU5DWV9SQVRFX0RFTEVURSIsIkNFUlRJRklDQVRFX0JMT0NLX0xJU1RfQ1JFQVRFIiwiQ0VSVElGSUNBVEVfQkxPQ0tfTElTVF9WSUVXX0FMTCIsIklTU1VFX0NFUlRJRklDQVRFX0JMT0NLX0xJU1RfVklFVyIsIkNFUlRJRklDQVRFX0JMT0NLX0xJU1RfVVBEQVRFIiwiQ0VSVElGSUNBVEVfVU5CTE9DS19MSVNUX0NSRUFURSIsIkFUVEVOREFOQ0VfT0ZGTElORV9RVUVVRV9DUkVBVEUiLCJBVFRFTkRBTkNFX09GRkxJTkVfUVVFVUVfVklFVyIsIkFUVEVOREFOQ0VfT0ZGTElORV9TWU5DIiwiQVRURU5EQU5DRV9PRkZMSU5FX1FVRVVFX0RFTEVURSIsIkFUVEVOREFOQ0VfVVBMT0FEX0NSRUFURSIsIkFUVEVOREFOQ0VfVVBMT0FEX1VQREFURSIsIkFUVEVOREFOQ0VfVVBMT0FEX1ZJRVciLCJBVFRFTkRBTkNFX0NTVl9QUk9DRVNTIiwiQVRURU5EQU5DRV9DT05GSUdfVklFVyIsIkFUVEVOREFOQ0VfQ09ORklHX1VQREFURSIsIkJPT0tfQ1JFQVRFIiwiQk9PS19WSUVXIiwiQk9PS19VUERBVEUiLCJCT09LX0RFTEVURSIsIkJPT0tfQ1FURUdPUllfQ1JFQVRFIiwiQk9PS19DQVRFR09SWV9WSUVXIiwiQk9PS19DQVRFR09SWV9VUERBVEUiLCJCT09LX0lTU1VFX1JFQ09SRF9DUkVBVEUiLCJCT09LX0lTU1VFX1JFQ09SRF9WSUVXIiwiQk9PS19JU1NVRV9SRUNPUkRfVVBEQVRFIiwiQk9PS19JU1NVRV9SRUNPUkRfREVMRVRFIiwiTElCUkFSWV9GSU5FX0NSRUFURSIsIkxJQlJBUllfRklORV9WSUVXIiwiTElCUkFSWV9GSU5FX1VQREFURSIsIkxJQlJBUllfRklORV9ERUxFVEUiLCJMSUJSQVJZX01FTUJFUl9DUkVBVEUiLCJMSUJSQVJZX01FTUJFUl9WSUVXIiwiTElCUkFSWV9NRU1CRVJfVVBEQVRFIiwiTElCUkFSWV9NRU1CRVJfREVMRVRFIiwiTElCUkFSWV9TRVRUSU5HX0NSRUFURSIsIkxJQlJBUllfU0VUVElOR19WSUVXIiwiTElCUkFSWV9TRVRUSU5HX1VQREFURSIsIkxJQlJBUllfU0VUVElOR19ERUxFVEUiLCJCT09LX0NBVEVHT1JZX0RFTEVURSIsIkJPT0tfUkVTRVJWQVRJT05fQ1JFQVRFIiwiQk9PS19SRVNFUlZBVElPTl9WSUVXIiwiSE9TVEVMX0NSRUFURSIsIkhPU1RFTF9WSUVXIiwiSE9TVEVMX1VQREFURSIsIkhPU1RFTF9ST09NX0NSRUFURSIsIkhPU1RFTF9ST09NX1ZJRVciLCJIT1NURUxfUk9PTV9VUERBVEUiLCJIT1NURUxfUk9PTV9ERUxFVEUiLCJIT1NURUxfQVRURU5EQU5DRV9NQVJLIiwiSE9TVEVMX0FUVEVOREFOQ0VfVklFVyIsIkhPU1RFTF9BVFRFTkRBTkNFX1VQREFURSIsIkhPU1RFTF9BVFRFTkRBTkNFX0RFTEVURSIsIkhPU1RFTF9BVFRFTkRBTkNFX0JVTEsiLCJIT1NURUxfQ09NUExBSU5UX0NSRUFURSIsIkhPU1RFTF9DT01QTEFJTlRfVklFVyIsIkhPU1RFTF9DT01QTEFJTlRfVVBEQVRFIiwiSE9TVEVMX0NPTVBMQUlOVF9TVEFUVVNfVVBEQVRFIiwiSE9TVEVMX0NPTVBMQUlOVF9SRU1BUksiLCJIT1NURUxfQ09NUExBSU5UX0RFTEVURSIsIkhPU1RFTF9BTExPQ0FUSU9OX0NSRUFURSIsIkhPU1RFTF9BTExPQ0FUSU9OX1ZJRVciLCJIT1NURUxfQUxMT0NBVElPTl9VUERBVEUiLCJIT1NURUxfQUxMT0NBVElPTl9TVEFUVVNfVVBEQVRFIiwiSE9TVEVMX0FMTE9DQVRJT05fUEFZTUVOVF9VUERBVEUiLCJIT1NURUxfQUxMT0NBVElPTl9ERUxFVEUiLCJNRVNTX01FTU5fQ1JFQVRFIiwiTUVTU19NRU5VX1ZJRVciLCJNRVNTX01FTU5fVVBEQVRFIiwiTUVTU19NRU5VX0RFTEVURSIsIkhPU1RFTF9WSVNJVF9DUkVBVEUiLCJIT1NURUxfVklTSVRfVklFVyIsIkhPU1RFTF9WSVNJVF9VUERBVEUiLCJIT1NURUxfVklTSVRfU1RBVFVTX1VQREFURSIsIkhPU1RFTF9WSVNJVF9DQU5DRUwiLCJIT1NURUxfVklTSVRfREVMRVRFIiwiSE9TVEVMX0hFQUxUSF9JTkNJREVOVF9DUkVBVEUiLCJIT1NURUxfSEVBTFRIX0lOQ0lERU5UX1ZJRVciLCJIT1NURUxfSEVBTFRIX0lOQ0lERU5UX1VQREFURSIsIkhPU1RFTF9IRUFMVEhfSU5DSURFTlRfU1RBVFVTX1VQREFURSIsIkhPU1RFTF9IRUFMVEhfSU5DSURFTlRfTk9URSIsIkhPU1RFTF9IRUFMVEhfSU5DSURFTlRfREVMRVRFIiwiRVhBTV9DUkVBVEUiLCJFWEFNX1VQREFURSIsIkVYQU1fUFVCTElTSCIsIkVYQU1fQ0xPU0UiLCJFWEFNX1ZJRVciLCJFWEFNX0RFU0lHTl9VUERBVEUiLCJFWEFNX0RFU0lHTl9WSUVXIiwiRVhBTV9TRVRUSU5HU19VUERBVEUiLCJFWEFNX1NFVFRJTkdTX1ZJRVciLCJFWEFNX1BST0NUT1JJTkdfVVBEQVRFIiwiRVhBTV9QUk9DVE9SSU5HX1ZJRVciLCJFWEFNX0dSQURJTkdfVVBEQVRFIiwiRVhBTV9HUkFESU5HX1ZJRVciLCJFWEFNX1JFU1VMVF9QVUJMSVNIIiwiRVhBTV9SRVNVTFRfSElERSIsIkVYQU1fTk9USUZJQ0FUSU9OX1VQREFURSIsIkVYQU1fTk9USUZJQ0FUSU9OX1ZJRVciLCJFWEFNX1FVRVNUSU9OX01BTkFHRSIsIkVYQU1fUVVFU1RJT05fVklFVyIsIlFVRVNUSU9OX09QVElPTl9NQU5BR0UiLCJRVUVTVElPTl9PUFRJT05fVklFVyIsIkVYQU1fQVRURU1QVF9WSUVXIiwiRVhBTV9BVFRFTVBUX0ZPUkNFX0NMT1NFIiwiRVhBTV9BVFRFTVBUX0FETUlOX1ZJRVciLCJFWEFNX1JFU1BPTlNFX0VWQUxVQVRFX1ZJRVciLCJFWEFNX1JFU1BPTlNFX0VWQUxVQVRFIiwiRVhBTV9WSU9MQVRJT05fVklFVyIsIkVYQU1fRVZBTFVBVElPTl9MT0dfQ1JFQVRFIiwiRVhBTV9FVkFMVUFUSU9OX0xPR19WSUVXIiwiSE9TVEVMX0ZFRV9DUkVBVEUiLCJIT1NURUxfRkVFX1ZJRVciLCJIT1NURUxfRkVFX1BBWU1FTlRfVVBEQVRFIiwiSE9TVEVMX0ZFRV9VUERBVEUiLCJIT1NURUxfRkVFX0RFTEVURSIsIkFTU0lHTk1FTlRfQUREIiwiQVNTSUdOTUVOVF9WSUVXIiwiQVNTSUdOTUVOVF9VUERBVEUiLCJBU1NJR05NRU5UX0RFTEVURSIsIkZVRUxfQUREIiwiRlVFTF9WSUVXIiwiRlVFTF9VUERBVEUiLCJGVUVMX0RFTEVURSIsIk1BSU5URU5BTkNFX0FERCIsIk1BSU5URU5BTkNFX1ZJRVciLCJVUERBVEVfTUFJTlRFTkFOQ0UiLCJNQUlOVEVOQU5DRV9ERUxFVEUiLCJGRUVfU1RSVUNUVVJFX0FERCIsIkZFRV9TVFJVQ1RVUkVfVklFVyIsIlBBWU1FTlRfQUREIiwiUEFZTUVOVF9WSUVXX0FMTCIsIlBBWU1FTlRfREVMRVRFIiwiVFJBTlNQT1JUX1NFVFRJTkdfVVBEQVRFIiwiVFJBTlNQT1JUX1NFVFRJTkdfVklFVyIsIkVYQU1fREVMRVRFIiwiRVhBTV9SRVNUT1JFIiwiRVhBTV9IQVJEX0RFTEVURSIsIlFVRVNUSU9OX0JBTktfTUFOQUdFIiwiUVVFU1RJT05fQkFOS19WSUVXIiwiUVVFU1RJT05fU0VDVElPTl9NQU5BR0UiLCJRVUVTVElPTl9TRUNUSU9OX1ZJRVciLCJTRUNUSU9OX01BTkFHRSIsIlNFU1RJT05fVklFVyIsIlFVRVNUSU9OX01BTkFHRSIsIlFVRVNUSU9OX1ZJRVciLCJFWEFNX1NDSEVEVUxFX0NSRUFURSIsIkVYQU1fU0NIRURVTEVfREVMRVRFIiwiRVhBTV9TQ0hFRFVMRV9SRVNUT1JFIiwiQ09ESU5HX1RFU1RfQ0FTRV9NQU5BR0UiLCJDT0RJTkdfVEVTVF9DQVNFX1ZJRVciLCJDRVJUSUZJQ0FURV9HRU5FUkFURSIsIkNFUlRJRklDQVRFX0JVTEtfR0VORVJBVEUiLCJDRVJUSUZJQ0FURV9SRVZPS0UiLCJDRVJUSUZJQ0FURV9SRU5FVyIsIkNFUlRJRklDQVRFX1VQREFURV9FWFBJUlkiLCJDRVJUSUZJQ0FURV9WSUVXX0FMTCIsIkNFUlRJRklDQVRFX1NUQVRTX1ZJRVciLCJDRVJUSUZJQ0FURV9TRU5EX0VNQUlMIiwiVklERU9fUFJPR1JFU1NfVVBEQVRFIiwiVklERU9fUFJPR1JFU1NfVklFVyIsIkNFUlRJRklDQVRFX1JVTEVfQ1JFQVRFIiwiQ0VSVElGSUNBVEVfUlVMRV9UT0dHTEUiLCJDRVJUSUZJQ0FURV9SVUxFX1ZJRVciLCJDRVJUSUZJQ0FURV9URU1QTEFURV9WSUVXIiwiQ0VSVElGSUNBVEVfVEVNUExBVEVfQ1JFQVRFIiwiQ0VSVElGSUNBVEVfVEVNUExBVEVfVVBEQVRFIiwiQ0VSVElGSUNBVEVfVEVNUExBVEVfREVMRVRFIiwiV0VCSU5BUl9WSUVXIiwiV0VCSU5BUl9DUkVBVEUiLCJXRUJJTkFSX1VQREFURSIsIldFQklOQVJfQ0FOQ0VMIiwiV0VCSU5BUl9MSVNUIiwiV0VCSU5BUl9WSUVXX1NDSEVEVUxFRCIsIkVYVEVSTkFMX1BBUlRJQ0lQQU5UX1ZJRVciLCJXRUJJTkFSX1JFR0lTVFJBVElPTl9WSUVXIiwiV0VCSU5BUl9SRUdJU1RSQVRJT05fQ0FOQ0VMIiwiV0VCSU5BUl9SRUdJU1RFUiIsIldFQklOQVJfQ0VRVUVTVF9WSUVXX1BFTkRJTkciLCJDRVJUSUZJQ0FURV9SRVFVRVNUX0FQUFJPVkUiLCJDRVJUSUZJQ0FURV9SRVFVRVNUX1JFUkVDVCIsIldFQklOQVJfUkVDT1JESU5HX1VQTE9BRCIsIldFQklOQVJfUkVDT1JESU5HX1ZJRVciLCJXRUJJTkFSX1JFQ09SRElOR19ERUxFVEUiLCJXRUJJTkFSX0NIQVRfU0VORCIsIldFQklOQVJfQ0hBVF9WSUVXIiwiV0VCSU5BUl9RVUVTVElPTl9BU0siLCJXRUJJTkFSX1FVRVNUSU9OX0FOU1dFUiIsIldFQklOQVJfUVVFU1RJT05fVklFVyIsIldFQklOQVJfUE9MTF9DUkVBVEUiLCJXRUJJTkFSX1BPTExfVklFVyIsIldFQklOQVJfUE9MTF9VUERBVEUiLCJXRUJJTkFSX1BPTExfERUxFVEUiLCJBRkZJTElBVEVfTUFOQUdFIiwiQUZGSUxJQVRFX0xJTktfR0VORVJBVEUiLCJBRkZJTElBVEVfVklFV19TRUxGIiwiQUZGSUxJQVRFX1ZJRVdfQUxMIiwiQUZGSUxJQVRFX1BBWU9VVCIsIkFGRklMSUFURV9MRUFEX1NVQk1JVCIsIldFQklOQVJfUE9MTF9SRVNQT05TRV9TVUJNSVQiLCJXRUJJTkFSX1BPTExfUkVTUE9OU0VfVklFVyIsIklURU1fQ1JFQVRFIiwiSVRFTV9WSUVXIiwiSVRFTV9VUERBVEUiLCJJVEVNX0RFTEVURSIsIlZFTkRPUl9DUkVBVEUiLCJWRU5ET1JfVklFVyIsIlZFTkRPUl9VUERBVEUiLCJWRU5ET1Jf0UxFVEUiLCJJTlZFTlRPUllfQ1JFQVRFIiwiSU5WRU5UT1JZX1ZJRVciLCJJTlZFTlRPUllfVVBEQVRFIiwiSU5WRU5UT1JZX0RFTEVURSIsIlNUT0NLX0lOV0FSRF9DUkVBVEUiLCJTVE9DS19JTldBUkRfVklFVyIsIkRJR0lUQUxfQVNTRVRfQ1JFQVRFIiwiRklHSVRBTF9BU1NFVF9WSUVXIiwiRklHSVRBTF9BU1NFVF9BU1NJR04iLCJDT1VSU0VfSU5WRU5UT1JZX0NSRUFURSIsIkNPVVJTRV9JTlZFTlRPUllfVklFVyIsIkNPVVJTRV9JTlZFTlRPUllfREVMRVRFIiwiQUxFUlRfVklFVyIsIklOVkVOVE9SWV9UUkFOU0FDU0lPTl9DUkVBVEUiLCJJTlZFTlRPUllfVFJBTlNBQ1RJT05fVklFVyIsIlJFVFVSTl9EQU1BR0VfQ1JFQVRFIiwiUkVUVVJOX0RBTUFHRV9WSUVXIiwiUkVQT1JUX0RBU0hCT0FSRF9WSUVXIiwiUkVQT1JUX1NUT0NLX1ZJRVciLCJSRVBPUlRfUFVSQ0hBU0VfVklFVyIsIlJFUE9SVF9JU1NVRV9WSUVXIiwiUkVQT1JUX0RBTUFHRV9WSUVXIiwiQUxFUlRfRURJVCIsIk1BUktFVElOR19BTkFMWVRJQ1NfVklFVyIsIk1BUktFVElOR19MQU5ESU5HX0NSRUFURSIsIk1BUktFVElOR19MQU5ESU5HX1ZJRVciLCJNQVJLRVRJTkdfTEFORElOR19VUERBVEUiLCJNQVJLRVRJTkdfTEFORElOR19ERUxFVEUiLCJNQVJLRVRJTkdfVFJBQ0tFRF9MSU5LX0NSRUFURSIsIk1BUktFVElOR19UUkFDS0VEX0xJTktfVklFVyIsIk1BUktFVElOR19UUkFDS0VEX0xJTktfREVMRVRFIiwiTUFSS0VUSU5HX0FOQUxZVElDU19TVU1NQVJZIiwiTUFSS0VUSU5HX0NBTVBBSUdOX0NSRUFURSIsIk1BUktFVElOR19DQU1QQUlHTl9WSUVXIiwiTUFSS0VUSU5HX0NBTVBBSUdOX1VQREFURSIsIk1BUktFVElOR19DQU1QQUlHTl9ERUxFVEUiLCJNQVJLRVRJTkdfQ0FNUEFJR05fRVhFQ1VURSIsIk1BUktFVElOR19DQU1QQUlHTl9JTVBPUlQiLCJNQVJLRVRJTkdfQ09OVEVOVF9DUkVBVEUiLCJNQVJLRVRJTkdfQ09OVEVOVF9WSUVXIiwiTUFSS0VUSU5HX0NPTlRFTlRfVVBEQVRFIiwiTUFSS0VUSU5HX0NPTlRFTlRfREVMRVRFIiwiTUFSS0VUSU5HX0NPVVBPTl9DUkVBVEUiLCJNQVJLRVRJTkdfQ09VUE9OX1VQREFURSIsIk1BUktFVElOR19DT1VQT05fU1RBVFVTIsIk1BUktFVElOR19DT1VQT05fREVMRVRFIiwiTUFSS0VUSU5HX0NPVVBPTl9WSUVXIiwiTUFSS0VUSU5HX0VNQUlMX1NFTkQiLCJNQVJLRVRJTkdfRU1BSUxfU0VORF9CVUxLIiwiTUFSS0VUSU5HX0lOVEVSQUNUSU9OX1ZJRVciLCJNQVJLRVRJTkdfTUVESUFfVVBMT0FEIiwiTUFSS0VUSU5HX01FRElBX1ZJRVciLCJNQVJLRVRJTkdfTk9USUZJQ0FUSU9OX1ZJRVciLCJNQVJLRVRJTkdfTk9USUZJQ0FUSU9OX1NFTkQiLCJSRUZFUlJBTF9TRUxGIiwiVFJBQ0tFRF9MSU5LX0NSRUFURSIsIlRSQUNLRURfTElOS19WSUVXIiwiVFJBQ0tFRF9MSU5LX0FOQUxZVElDU19WSUVXIiwiVFJBQ0tFRF9MSU5LX0RFTEVURSIsIkFGRklMSUFURV9DUkVBVEUiLCJBRkZJTElBVEVfVklFVyIsIkFGRklMSUFURV9VUERBVEUiLCJBRkZJTElBVEVfTElOS19DUkVBVEUiLCJBRkZJTElBVEVfTEVBRF9WSUVXIiwiQUZGSUxJQVRFX0xFQURfVVBEQVRFIiwiQUZGSUxJQVRFX0xFQURfTk9URV9DUkVBVEUiLCJBRkZJTElBVEVfTEVBRF9FWFBPUlQiLCJBRkZJTElBVEVfU0FMRV9WSUVXIiwiQUZGSUxJQVRFX1NBTEVfQ1JFQVRFIiwiQUZGSUxJQVRFX1NBTEVfQVBQUFJPVkUiLCJBRkZJTElBVEVfU0FMRV9DQU5DRUwiLCJBRkZJTElBVEVfU0FMRV9QQVkiLCJBRkZJTElBVEVfU0FMRV9FWFBPUlQiLCJBRkZJTElBVEVfUE9SVEFMX1ZJRVciLCJDT01NSVNTSU9OX1JVTUVfVklFVyIsIkNPTU1JU1NJT05fUlVMRV9DUkVBVEUiLCJDT01NSVNTSU9OX1JVTEVfVVBEQVRFIiwiQ09NTUlTU0lPTl9SVUxFX0RFTEVURSIsIlBBWU9VVF9WSUVXX0FMTCIsIldBTEhFVF9WSUVXX0FMTCIsIldBTEhFVF9DT05GSUdfVklFVyIsIldBTEhFVF9DT05GSUdfVVBEQVRFIiwiRkVFX0FDQ09VTlRfU1VNTUFSWV9WSUV3IiwiRUFSTFlfUEFZTUVOVF9DUkVBVEUiLCJFQVJMWV9QQVlNRU5UX1ZJRVciLCJFQVJMWV9QQVlNRU5UX0xPQ0tfTUFOT0UiLCJFQVJMWV9QQVlNRU5UX1NZTkMiLCJJTlNUQUxMTUVOVF9DUkVBVEUiLCJBVURJVF9MT0dfVklFVyIsIkRJU0NPVU5UX0NSRUFURSIsIkRJU0NPVU5UX1ZJRVciLCJESVNDT1VOVF9WSUVXX1VTRVIiLCJESVNDT1VOVF9VUERBVEUiLCJESVNDT1VOVF9ERUxFVEUiLCJMQVRFX0ZFRV9DUkVBVEUiLCJMQVRFX0ZFRV9WSUVXIiwiTEFURV9GRUVfVVBEQVRFIiwiTEFURV9GRUVfREVMRVRFIiwiTEFURV9GRUVfUEVOQUxUWV9WSUVXIiwiTEFURV9GRUVfUEVOQUxUWV9XQUlWRSIsIk1BU1RFUl9TRVRUSU5HU19HTE9CQUxfU0FWRSIsIk1BU1RFUl9TRVRUSU5HU19HTE9CQUxfVklFVyIsIlBBWU1FTlRfQlVMS19DQUxDVUxBVEUiLCJQQVlNRU5UX0JVTEtfUFJPQ0VTUyIsIlBBWU1FTlRfVklFVyIsIlBBWU1FTlRfQ1JFQVRFIiwiUEFZTUVOVF9SRUNFSVBUX1ZJRVciLCJQQVlNRU5UX0ZJTEVfVVBMT0FEIiwiUEFZTUVOVF9TWU5DIiwiUkVGVU5EX1JVTEVfQ1JFQVRFIiwiUkVGVU5EX1JVTEVfVklFVyIsIlJFRlVORF9SVUxFX1VQREFURSIsIlJFRlVORF9SVUxFX0RFTEVURSIsIkFMTE9DQVRJT05fVklFVyIsIkFMTE9DQVRJT05fQ1JFQVRFIiwiQUxMT0NBVElPTl9VUERBVEUiLCJBTExPQ0FUSU9OX0RFTEVURSIsIkFMTE9DQVRJT05fU1lOQyIsIlJFRlVORF9WSUVXIiwiUkVGVU5EX0FQUFJPVkUiLCJSRUZVTkRfUkVKRUNUIiwiUkVGVU5EX0RFTEVURSIsIklOU1RBTExNRU5UX1JFU1BETyIsIklOU1RBTExNRU5UX1ZJRVciLCJJTlNUQUxMTUVOVF9WSUVXX09WRVJEVUUiLCJJTlNUQUxMTUVOVF9ERUxFVEUiLCJJTlNUQUxMTUVOVF9FWFRFTkQiLCJTWVNURU1fU0VUVElOR19WSUVXIiwiU1lTVEVNX1NFRFRSU0dfVVBEQVRFIiwiTUFTVEVSX1NFVFRJTkdTX1VQREFURSIsIk1BU1RFUl9TRVRUSU5HU19WSUVXIiwiTk9USUZJQ0FUSU9OX0NSRUFURSIsIk5PVElGSUNBVElPTl9WSUVXIiwiTk9USUZJQ0FUSU9OX1ZJRVdfVVNFUklEIiwiTk9USUZJQ0FUSU9OX1VQREFURSIsIk5PVElGSUNBVElPTl9ERUxFVEUiLCJOT1RJRklDQVRJT05fU0VORF9QQVlNRU5UIl0sImlhdCI6MTc3NDUxMDUxMn0.Qudu6be8UyuhjqFuVQkcnQKWdIhFpOcEjLLOdrIzk3F99oMvfJcllFVrs3jiwVJk_RyMK7OtX4tdL0CZSxw-pw';

let currentToken = INSTRUCTOR_TOKEN;
let examId = null;
let sectionId = null;
let importedQuestionIds = [];
let studentToken = null;
let attemptId = null;

const api = axios.create({
    baseURL: API_BASE,
    headers: { 
        'Content-Type': 'application/json',
        'Origin': 'http://localhost:5173',
        'Referer': 'http://localhost:5173/',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
    }
});

api.interceptors.request.use(config => {
    if (currentToken) config.headers.Authorization = `Bearer ${currentToken}`;
    // Based on the 'admin@gmail.com' sub, the tenant is 'gmail'.
    // However, we saw 'classx360' and 'vignesh' previously. 
    // We will use 'classx360' as the most likely candidate for Step 1.
    config.headers['X-Tenant-DB'] = 'classx360'; 
    return config;
});

async function runStep(id, title, fn) {
    console.log(`\n>>> STARTING STEP ${id}: ${title}`);
    try {
        const res = await fn();
        console.log(`[SUCCESS] STEP ${id} completed.`);
        return res;
    } catch (err) {
        console.error(`[FAILURE] STEP ${id}:`, err.response?.data || err.message);
        // If 431, suggest increasing header size
        if (err.message.includes('431')) {
           console.error("TIP: Use 'node --max-http-header-size=65536 exam_setup.cjs'");
        }
        return null;
    }
}

async function main() {
    // PART 1: EXAM SETUP
    await runStep(1, 'Create Base Exam', async () => {
        const res = await api.post('/api/exams', {
            examType: "MOCK",
            title: "Full Stack Final Assessment " + Date.now(),
            totalMarks: 100,
            passPercentage: 40.0,
            durationMinutes: 60,
            certificateEnabled: true
        });
        examId = res.data.examId || res.data.id;
        console.log(`Created Exam ID: ${examId}`);
    });

    if (!examId) {
        console.error("FATAL: Could not proceed without Exam ID. Retrying with tenant 'vignesh'...");
        // RETRY with different tenant
        try {
           const res = await axios.post(API_BASE + '/api/exams', {
                examType: "MOCK",
                title: "Full Stack Final Retried " + Date.now(),
                totalMarks: 100, passPercentage: 40.0, durationMinutes: 60, certificateEnabled: true
           }, { headers: { Authorization: `Bearer ${currentToken}`, 'X-Tenant-DB': 'vignesh' } });
           examId = res.data.examId || res.data.id;
           console.log(`RETRY SUCCESS! Created Exam ID: ${examId} (Tenant: vignesh)`);
        } catch (e) {
           console.error("RETRY FAILED: Still 403 or other error.");
        }
    }

    if (examId) {
        await runStep(2, 'Configure Exam Settings', () => api.post(`/api/exams/${examId}/settings`, {
            allowResume: true, allowNavigation: true, shuffleQuestions: true, calculatorEnabled: false, strictTimeline: true, canSubmitBeforeEnd: true
        }));

        await runStep(3, 'Configure Grading Rules', () => api.post(`/api/exams/${examId}/grading`, {
            autoEvaluation: true, partialMarking: true, showResult: true, showRank: false, showPercentile: false
        }));

        await runStep(4, 'Configure Proctoring Rules', () => api.post(`/api/exams/${examId}/proctoring`, {
            cameraRequired: true, faceDetection: true, tabSwitchLimit: 3, screenSharingRequired: false, browserLock: false
        }));

        await runStep(5, 'Upload Exam Design', async () => {
            const form = new FormData();
            const designPath = path.join(__dirname, 'exam_design_1774509237393.png');
            if (fs.existsSync(designPath)) {
                form.append('design', fs.createReadStream(designPath));
                await api.post(`/api/exams/${examId}/design`, form, { headers: { ...form.getHeaders(), 'X-Tenant-DB': 'vignesh' } });
            }
        });

        await runStep(6, 'Configure Notification Settings', () => api.post(`/api/exams/${examId}/notification`, {
            emailEnabled: true, smsEnabled: false, pushEnabled: true, reminderMinutes: 30
        }));

        // PART 2: QUESTION BANK
        await runStep(7, 'Bulk Import Questions', async () => {
            const form = new FormData();
            const csvPath = path.join(__dirname, 'question_bank.csv');
            if (fs.existsSync(csvPath)) {
                form.append('file', fs.createReadStream(csvPath));
                const res = await api.post('/api/questions/import', form, { headers: { ...form.getHeaders(), 'X-Tenant-DB': 'vignesh' } });
                if (res.data && Array.isArray(res.data)) {
                    importedQuestionIds = res.data.map(q => q.id || q.questionId);
                }
            }
        });

        await runStep(8, 'Create Mapping Section', async () => {
            const res = await api.post(`/api/exams/${examId}/sections`, {
                sectionName: "Main Content", totalQuestions: 5, marksPerQuestion: 20
            });
            sectionId = res.data.examSectionId || res.data.id;
        });

        if (sectionId && importedQuestionIds.length > 0) {
            await runStep(9, 'Map Questions to Section', () => api.post(`/api/exams/${examId}/sections/${sectionId}/questions/map`, {
                questionIds: importedQuestionIds.slice(0, 5)
            }));
        }

        // PART 3: SCHEDULING
        await runStep(10, 'Link Exam to Course', () => api.post(`/api/exams/${examId}/course-link`, {
            courseId: 1, isMandatory: true
        }));

        await runStep(11, 'Publish Exam Schedule', () => api.post('/api/exam-schedules', {
            examId: examId, batchId: 1, startTime: new Date().toISOString(), endTime: new Date(Date.now() + 86400000).toISOString()
        }));

        await runStep(12, 'Verify Published State', () => api.get(`/api/exams/${examId}`));

        // PART 4: STUDENT ATTEMPT
        await runStep(13, 'Login as Student', async () => {
            const res = await axios.post(`${API_BASE}/api/auth/login`, {
                email: "srdsantoshchavithini@gmail.com",
                password: "password123"
            });
            studentToken = res.data.token || res.data.jwt || res.data;
            currentToken = studentToken;
        });

        if (studentToken) {
            await runStep(14, 'Start Exam Attempt', async () => {
                const res = await api.post(`/api/exams/${examId}/attempts/start`, {});
                attemptId = res.data.attemptId || res.data.id;
            });

            if (attemptId) {
                await runStep(15, 'Submit Answers', () => api.post(`/api/exams/${examId}/attempts/${attemptId}/submit`, {
                    responses: [{ questionId: importedQuestionIds[0] || 1, selectedOption: "Paris" }]
                }));
            }
        }

        // PART 5: EVALUATION
        currentToken = INSTRUCTOR_TOKEN;
        await runStep(16, 'Fetch Submissions', () => api.get(`/api/exams/${examId}/attempts`));

        if (attemptId) {
            await runStep(17, 'Manual Grade Entry', () => api.post(`/api/evaluations`, {
                attemptId: attemptId, evaluations: [{ questionId: importedQuestionIds[0] || 1, marks: 10, feedback: "Excellent" }]
            }));
        }

        await runStep(18, 'Finalize Results', () => api.post(`/api/exams/${examId}/finalize`, {
            publishResults: true, generateCertificates: true
        }));
    }

    console.log("\n--- AUTOMATION WORKFLOW FINISHED ---");
}

main();
